export const chakraSeeds = [
  { name: "mooladhara", displayName: "Mooladhara Chakra", description: "May relate to innocence, purity, groundedness, and stability.", qualities: ["Innocence", "Purity", "Groundedness"], catchingIndicators: ["Restlessness", "Lack of grounding"], iconName: "lotus-root", color: "#C0392B" },
  { name: "swadhisthana", displayName: "Swadhisthana Chakra", description: "May relate to creativity, attention, and mental overactivity.", qualities: ["Creativity", "Pure knowledge", "Attention"], catchingIndicators: ["Overplanning", "Mental overuse"], iconName: "lotus-orange", color: "#E67E22" },
  { name: "nabhi", displayName: "Nabhi Chakra", description: "May relate to satisfaction, nourishment, and wellbeing in daily life.", qualities: ["Satisfaction", "Peace", "Dharma"], catchingIndicators: ["Dissatisfaction", "Digestive imbalance"], iconName: "lotus-gold", color: "#F1C40F" },
  { name: "void", displayName: "Void", description: "May relate to household peace, belonging, and guru principle.", qualities: ["Balance", "Guidance", "Belonging"], catchingIndicators: ["Insecurity", "Disconnection"], iconName: "lotus-white", color: "#D4AF37" },
  { name: "heart", displayName: "Heart Chakra", description: "May relate to love, confidence, and security.", qualities: ["Love", "Confidence", "Security"], catchingIndicators: ["Fear", "Insecurity"], iconName: "lotus-green", color: "#2E7D4F" },
  { name: "vishuddhi", displayName: "Vishuddhi Chakra", description: "May relate to communication, collectivity, and guilt.", qualities: ["Communication", "Respect", "Witness state"], catchingIndicators: ["Guilt", "Throat discomfort"], iconName: "lotus-blue", color: "#1A3557" },
  { name: "agnya", displayName: "Agnya Chakra", description: "May relate to forgiveness, clarity, and freedom from conditioning.", qualities: ["Forgiveness", "Humility", "Clarity"], catchingIndicators: ["Resentment", "Pressure in head"], iconName: "lotus-indigo", color: "#5B4B8A" },
  { name: "sahasrara", displayName: "Sahasrara Chakra", description: "May relate to integration, connection, and silent awareness.", qualities: ["Integration", "Silence", "Divine connection"], catchingIndicators: ["No vibrations", "Lack of connection"], iconName: "lotus-violet", color: "#8E44AD" },
];

export const nadiSeeds = [
  { name: "leftNadi", displayName: "Left Channel / Ida Nadi", description: "May reflect emotional heaviness, past orientation, or low energy.", characteristics: ["Past-oriented", "Emotionally sensitive", "Cooling"], catchingIndicators: ["Sadness", "Heaviness", "Coldness"], color: "#4F7CAC" },
  { name: "rightNadi", displayName: "Right Channel / Pingala Nadi", description: "May reflect overactivity, future planning, or heat.", characteristics: ["Active", "Future-oriented", "Heating"], catchingIndicators: ["Heat", "Overthinking", "Irritation"], color: "#D4500A" },
  { name: "centerNadi", displayName: "Center Channel / Sushumna Nadi", description: "May reflect balance, meditation depth, and centered attention.", characteristics: ["Balanced", "Present", "Steady"], catchingIndicators: ["General imbalance only when disturbed"], color: "#2E7D4F" },
];

export const contentSeeds = [
  { key: "homeIntro", title: "Home Intro", content: "This supportive Sahajayoga guidance tool invites you to answer calmly and honestly. Based on your answers, it may suggest which chakra or channel may need attention and which simple remedies or mantras may help." },
  { key: "fullDisclaimer", title: "Full Disclaimer", content: "This tool offers supportive guidance based on the answers you provide. The result may not always be fully accurate and should not be understood as a definitive spiritual assessment. For deeper clarity, please connect with experienced Sahajayogis." },
  { key: "shortDisclaimer", title: "Short Disclaimer", content: "This result is based on your selected answers and may not always be fully accurate. For deeper guidance, please connect with experienced Sahajayogis." },
  { key: "centeringText", title: "Centering Text", content: "Please close your eyes for a moment, place your attention on your Sahasrara, and answer from your heart, not from your mind." },
  { key: "finalGuidance", title: "Final Guidance", content: "Take this guidance gently. Regular meditation, footsoak, bandhan, and connection with the collective may help bring balance." },
  { key: "inconclusiveGuidance", title: "Inconclusive Guidance", content: "Your answers show a mixed pattern. A general cleansing approach, daily meditation, and guidance from experienced Sahajayogis may help more than focusing on one specific area." },
];

export const questionsSeed = [
  {
    sortOrder: 1,
    category: "vibration",
    type: "single-choice",
    questionText: "Where do you feel catching or discomfort most?",
    helpText: "For new seekers, choose 'Not sure' if you do not understand vibrations yet.",
    templateKeys: ["beginner_sahajayogi", "regular_sahajayogi", "advanced_vibration_guidance"],
    audienceTypes: ["beginner", "regular", "advanced"],
    difficultyLevel: "intermediate",
    options: [
      { label: "Left hand or left side of body", value: "left-side", nadiScores: { leftNadi: 3 } },
      { label: "Right hand or right side of body", value: "right-side", nadiScores: { rightNadi: 3 } },
      { label: "Both hands equally", value: "both", nadiScores: { centerNadi: 1, leftNadi: 1, rightNadi: 1 } },
      { label: "Crown or top of head", value: "crown", chakraScores: { sahasrara: 2 } },
      { label: "Chest or heart area", value: "heart-area", chakraScores: { heart: 2 } },
      { label: "Not sure / No clear sensation", value: "neutral", isNeutral: true },
    ],
  },
  {
    sortOrder: 2,
    category: "vibration",
    type: "intensity",
    questionText: "How intense is the sensation or catching you feel?",
    helpText: "1 is very mild and 5 is very strong. This only adjusts the first question.",
    templateKeys: ["beginner_sahajayogi", "regular_sahajayogi", "advanced_vibration_guidance"],
    audienceTypes: ["beginner", "regular", "advanced"],
    difficultyLevel: "intermediate",
    options: [
      { label: "1 — Very mild", value: "1", multiplierValue: 0.5 },
      { label: "2 — Mild", value: "2", multiplierValue: 0.75 },
      { label: "3 — Moderate", value: "3", multiplierValue: 1 },
      { label: "4 — Strong", value: "4", multiplierValue: 1.25 },
      { label: "5 — Very strong", value: "5", multiplierValue: 1.5 },
    ],
  },
  {
    sortOrder: 3,
    category: "vibration",
    type: "single-choice",
    questionText: "What sensation do you feel most during or after meditation?",
    templateKeys: ["beginner_sahajayogi", "regular_sahajayogi", "advanced_vibration_guidance"],
    audienceTypes: ["beginner", "regular", "advanced"],
    difficultyLevel: "intermediate",
    options: [
      { label: "Heat in hands or head", value: "heat", nadiScores: { rightNadi: 2 }, chakraScores: { agnya: 1 } },
      { label: "Cool breeze on palms or crown", value: "cool", nadiScores: { centerNadi: 1 } },
      { label: "Tingling or pins and needles", value: "tingling", chakraScores: { sahasrara: 1 } },
      { label: "Numbness or heaviness", value: "numb", nadiScores: { leftNadi: 2 } },
      { label: "Restlessness or cannot sit still", value: "restless", nadiScores: { rightNadi: 1 }, chakraScores: { agnya: 1 } },
      { label: "No sensation at all", value: "none", chakraScores: { sahasrara: 1 } },
      { label: "I do not meditate regularly", value: "neutral", isNeutral: true },
    ],
  },
  {
    sortOrder: 4,
    category: "emotional",
    type: "multiple-choice",
    questionText: "Which feelings best match your current emotional state? Select all that apply.",
    templateKeys: ["new_seeker_basic", "beginner_sahajayogi", "regular_sahajayogi", "advanced_vibration_guidance"],
    audienceTypes: ["newSeeker", "beginner", "regular", "advanced"],
    difficultyLevel: "basic",
    options: [
      { label: "Fear or anxiety", value: "fear", chakraScores: { heart: 2, mooladhara: 1 } },
      { label: "Guilt or feeling unworthy", value: "guilt", chakraScores: { vishuddhi: 2 } },
      { label: "Sadness or feeling low", value: "sadness", nadiScores: { leftNadi: 2 }, chakraScores: { nabhi: 1 } },
      { label: "Anger or irritation", value: "anger", nadiScores: { rightNadi: 2 }, chakraScores: { nabhi: 1 } },
      { label: "Emotional heaviness or grief", value: "grief", nadiScores: { leftNadi: 2 }, chakraScores: { heart: 1 } },
      { label: "Insecurity or lack of confidence", value: "insecurity", chakraScores: { heart: 2 } },
      { label: "Peaceful and settled", value: "peaceful", nadiScores: { centerNadi: 1 } },
      { label: "Not sure / Mixed feelings", value: "neutral", isNeutral: true },
    ],
  },
  {
    sortOrder: 5,
    category: "mental",
    type: "multiple-choice",
    questionText: "What best describes your mind today? Select all that apply.",
    templateKeys: ["new_seeker_basic", "beginner_sahajayogi", "regular_sahajayogi", "advanced_vibration_guidance"],
    audienceTypes: ["newSeeker", "beginner", "regular", "advanced"],
    difficultyLevel: "basic",
    options: [
      { label: "Too much thinking or overactive mind", value: "overthinking", nadiScores: { rightNadi: 2 }, chakraScores: { swadhisthana: 1 } },
      { label: "Planning too much or future-focused", value: "future", chakraScores: { swadhisthana: 2 }, nadiScores: { rightNadi: 1 } },
      { label: "Confusion or lack of clarity", value: "confusion", chakraScores: { agnya: 2 } },
      { label: "Pressure or heaviness in the head", value: "pressure", chakraScores: { agnya: 2, sahasrara: 1 } },
      { label: "Negative thoughts or past memories", value: "past", nadiScores: { leftNadi: 2 }, chakraScores: { agnya: 1 } },
      { label: "Cannot forgive someone or myself", value: "forgive", chakraScores: { agnya: 2 } },
      { label: "Calm and clear", value: "calm", nadiScores: { centerNadi: 1 } },
      { label: "Distracted or unfocused", value: "distracted", chakraScores: { sahasrara: 1, swadhisthana: 1 } },
    ],
  },
  {
    sortOrder: 6,
    category: "meditation",
    type: "single-choice",
    questionText: "How has your meditation or quiet sitting been recently?",
    templateKeys: ["new_seeker_basic", "beginner_sahajayogi", "regular_sahajayogi", "advanced_vibration_guidance"],
    audienceTypes: ["newSeeker", "beginner", "regular", "advanced"],
    difficultyLevel: "basic",
    options: [
      { label: "Deep and peaceful", value: "deep", nadiScores: { centerNadi: 2 } },
      { label: "Distracted — mind keeps wandering", value: "wandering", chakraScores: { sahasrara: 1, swadhisthana: 1 } },
      { label: "Too many thoughts — cannot go beyond", value: "thoughts", nadiScores: { rightNadi: 2 }, chakraScores: { agnya: 1 } },
      { label: "Sleepy or dull — no energy", value: "sleepy", nadiScores: { leftNadi: 2 } },
      { label: "No vibrations or cannot feel anything", value: "no-vibrations", chakraScores: { sahasrara: 2 } },
      { label: "Cannot sit properly — restless body", value: "restless", nadiScores: { rightNadi: 1 }, chakraScores: { mooladhara: 1 } },
      { label: "Have not been meditating regularly", value: "neutral", isNeutral: true },
    ],
  },
  {
    sortOrder: 7,
    category: "life-area",
    type: "multiple-choice",
    questionText: "Which life areas feel disturbed or unsettled currently? Select all that apply.",
    templateKeys: ["new_seeker_basic", "beginner_sahajayogi", "regular_sahajayogi", "advanced_vibration_guidance"],
    audienceTypes: ["newSeeker", "beginner", "regular", "advanced"],
    difficultyLevel: "basic",
    options: [
      { label: "Innocence, purity, or groundedness", value: "mooladhara", chakraScores: { mooladhara: 2 } },
      { label: "Creativity, attention, or worldly desires", value: "swadhisthana", chakraScores: { swadhisthana: 2 } },
      { label: "Satisfaction, nourishment, or household peace", value: "nabhi", chakraScores: { nabhi: 2 } },
      { label: "Security, family, or sense of belonging", value: "void", chakraScores: { void: 2, heart: 1 } },
      { label: "Love, confidence, or feeling accepted", value: "heart", chakraScores: { heart: 2 } },
      { label: "Communication, expression, or guilt", value: "vishuddhi", chakraScores: { vishuddhi: 2 } },
      { label: "Forgiveness, ego, or past conditioning", value: "agnya", chakraScores: { agnya: 2 } },
      { label: "Peace, integration, or connection to Divine", value: "sahasrara", chakraScores: { sahasrara: 2 } },
      { label: "Nothing specific is disturbed right now", value: "neutral", isNeutral: true },
    ],
  },
  {
    sortOrder: 8,
    category: "mental",
    type: "single-choice",
    questionText: "Is there someone in your life you are finding very difficult to forgive?",
    templateKeys: ["new_seeker_basic", "beginner_sahajayogi", "regular_sahajayogi", "advanced_vibration_guidance"],
    audienceTypes: ["newSeeker", "beginner", "regular", "advanced"],
    difficultyLevel: "basic",
    options: [
      { label: "Yes — strongly", value: "strongly", chakraScores: { agnya: 3 } },
      { label: "Yes — mildly", value: "mildly", chakraScores: { agnya: 1 } },
      { label: "No", value: "no" },
      { label: "Not applicable", value: "neutral", isNeutral: true },
    ],
  },
  {
    sortOrder: 9,
    category: "physical",
    type: "multiple-choice",
    questionText: "Do you experience any of these physical symptoms regularly? Select all that apply.",
    templateKeys: ["new_seeker_basic", "beginner_sahajayogi", "regular_sahajayogi", "advanced_vibration_guidance"],
    audienceTypes: ["newSeeker", "beginner", "regular", "advanced"],
    difficultyLevel: "basic",
    options: [
      { label: "Headaches or pressure on crown", value: "headache", chakraScores: { sahasrara: 1, agnya: 1 } },
      { label: "Neck or throat discomfort", value: "throat", chakraScores: { vishuddhi: 2 } },
      { label: "Chest tightness or heart palpitations", value: "chest", chakraScores: { heart: 2 } },
      { label: "Stomach discomfort or digestive issues", value: "stomach", chakraScores: { nabhi: 2 } },
      { label: "Lower back or pelvic area discomfort", value: "lower-back", chakraScores: { mooladhara: 1, swadhisthana: 1 } },
      { label: "Cold hands or feet", value: "cold", nadiScores: { leftNadi: 1 } },
      { label: "Excessive heat in body or hot flushes", value: "heat", nadiScores: { rightNadi: 2 } },
      { label: "None of these", value: "neutral", isNeutral: true },
    ],
  },
  {
    sortOrder: 10,
    category: "spiritual",
    type: "multiple-choice",
    questionText: "How would you describe your connection to the Divine or to Sahajayoga recently? Select all that apply.",
    templateKeys: ["new_seeker_basic", "beginner_sahajayogi", "regular_sahajayogi", "advanced_vibration_guidance"],
    audienceTypes: ["newSeeker", "beginner", "regular", "advanced"],
    difficultyLevel: "basic",
    options: [
      { label: "Strong and growing", value: "strong", nadiScores: { centerNadi: 2 }, chakraScores: { sahasrara: 1 } },
      { label: "Inconsistent", value: "inconsistent", chakraScores: { sahasrara: 1 } },
      { label: "Weak", value: "weak", chakraScores: { sahasrara: 2 } },
      { label: "I have been doubting or questioning", value: "doubting", chakraScores: { agnya: 2, sahasrara: 1 } },
      { label: "I am new and still learning", value: "neutral", isNeutral: true },
    ],
  },
  {
    sortOrder: 11,
    category: "channel-tendency",
    type: "multiple-choice",
    questionText: "Which of the following patterns describe you recently? Select all that apply.",
    templateKeys: ["new_seeker_basic", "beginner_sahajayogi", "regular_sahajayogi", "advanced_vibration_guidance"],
    audienceTypes: ["newSeeker", "beginner", "regular", "advanced"],
    difficultyLevel: "basic",
    options: [
      { label: "I have been very active, busy, driven, doing too much", value: "active", nadiScores: { rightNadi: 3 } },
      { label: "I have been withdrawn, passive, low energy, or depressed", value: "withdrawn", nadiScores: { leftNadi: 3 } },
      { label: "I have been balanced — neither extreme", value: "balanced", nadiScores: { centerNadi: 2 } },
      { label: "I tend to live in the past, old memories come often", value: "past", nadiScores: { leftNadi: 2 } },
      { label: "I tend to plan ahead too much, always thinking of future", value: "future", nadiScores: { rightNadi: 2 } },
      { label: "Not sure", value: "neutral", isNeutral: true },
    ],
  },
  {
    sortOrder: 12,
    category: "joy",
    type: "multiple-choice",
    questionText: "How do you feel about your overall sense of satisfaction and joy? Select all that apply.",
    templateKeys: ["new_seeker_basic", "beginner_sahajayogi", "regular_sahajayogi", "advanced_vibration_guidance"],
    audienceTypes: ["newSeeker", "beginner", "regular", "advanced"],
    difficultyLevel: "basic",
    options: [
      { label: "Very satisfied and joyful", value: "joyful", nadiScores: { centerNadi: 2 }, chakraScores: { nabhi: 1 } },
      { label: "Somewhat satisfied", value: "somewhat", isNeutral: true },
      { label: "Lacking joy or feeling dry inside", value: "dry", chakraScores: { nabhi: 2 } },
      { label: "Dissatisfied — things do not feel right", value: "dissatisfied", chakraScores: { nabhi: 2 }, nadiScores: { leftNadi: 1 } },
      { label: "Seeking — I want more meaning", value: "seeking", chakraScores: { sahasrara: 1 } },
    ],
  },
];