name: Deploy Self Introspect

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            set -e

            echo "Go to project folder"
            cd /var/www/selfintrospect.my

            echo "Pull latest code"
            git pull origin main

            echo "Install backend dependencies"
            cd backend
            npm install

            echo "Restart backend"
            pm2 restart self-introspect-api || pm2 start server.js --name self-introspect-api

            echo "Install frontend dependencies"
            cd ../frontend
            npm install

            echo "Build frontend"
            npm run build

            echo "Copy frontend build"
            rm -rf /var/www/self-introspect-frontend/*
            cp -r dist/* /var/www/self-introspect-frontend/

            echo "Save PM2 and reload NGINX"
            pm2 save
            nginx -t
            systemctl reload nginx